#!/usr/bin/env python3
"""Check that every internal link in the built site resolves — anchors included.

Run it against the output of `mkdocs build`:

    python tools/check_links.py site

Why the built HTML rather than the markdown sources? Two reasons, both of which
have bitten this book already:

* Heading anchors are generated by the slugifier, so checking markdown means
  reimplementing that slugifier and hoping the copy stays faithful. Reading the
  emitted `id="..."` attributes needs no such guess.
* Under `/nb/`, mkdocs-static-i18n has already decided whether each page is the
  Norwegian translation or the English fallback. A link written
  `control_statements.md#range-based-for` resolves to the *Norwegian* page,
  whose heading slug is `#range-basert-for` — so the anchor silently breaks and
  the reader lands at the top of the page. Nothing in the build warns about it.
  Checking the built tree catches exactly this.

Exits non-zero if anything is unresolved, so CI fails on a broken link.
"""

import argparse
import os
import re
import sys
from urllib.parse import unquote, urlparse

ID_RE = re.compile(r'\bid="([^"]+)"')
HREF_RE = re.compile(r'<a\b[^>]*?href="([^"]+)"', re.IGNORECASE)
ARTICLE_RE = re.compile(r"<article\b.*?</article>", re.DOTALL)

# Schemes that are somebody else's problem.
EXTERNAL = ("http:", "https:", "mailto:", "tel:", "javascript:", "data:", "//")


def collect(site_dir):
    """Map each built page to its element ids, and gather every link it makes."""
    pages, links = {}, []
    for root, _dirs, files in os.walk(site_dir):
        for name in files:
            if not name.endswith(".html"):
                continue
            full = os.path.join(root, name)
            rel = os.path.relpath(full, site_dir).replace(os.sep, "/")
            html = open(full, encoding="utf-8").read()

            # Ids come from the whole page; links only from the article body, so
            # the theme's own chrome (nav, tabs, search) is not under test.
            pages[rel] = set(ID_RE.findall(html))
            match = ARTICLE_RE.search(html)
            for href in HREF_RE.findall(match.group(0) if match else html):
                links.append((rel, href))
    return pages, links


def resolve(from_page, href):
    """Return (target page, fragment) for a link found on `from_page`."""
    parsed = urlparse(href)
    path, frag = parsed.path, unquote(parsed.fragment)
    if not path:
        return from_page, frag
    base = os.path.dirname(from_page)
    target = os.path.normpath(os.path.join(base, path)).replace(os.sep, "/")
    if not target.endswith(".html"):
        target = target.rstrip("/") + "/index.html"
    return target, frag


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("site", nargs="?", default="site", help="built site directory")
    args = ap.parse_args()

    if not os.path.isdir(args.site):
        sys.exit(f"error: '{args.site}' is not a directory — run `mkdocs build` first")

    pages, links = collect(args.site)
    missing_page, missing_anchor = [], []

    for from_page, href in links:
        if href.startswith(EXTERNAL) or href == "#":
            continue
        target, frag = resolve(from_page, href)
        if target not in pages:
            missing_page.append((from_page, href))
        elif frag and frag not in pages[target]:
            missing_anchor.append((from_page, href))

    print(f"pages scanned : {len(pages)}")
    print(f"links checked : {len(links)}")

    for label, rows in (("BROKEN LINK", missing_page), ("BROKEN ANCHOR", missing_anchor)):
        for page, href in rows:
            print(f"  {label}: {page} -> {href}")

    total = len(missing_page) + len(missing_anchor)
    if total:
        print(f"\nFAILED: {len(missing_page)} broken link(s), "
              f"{len(missing_anchor)} broken anchor(s)")
        return 1
    print("OK: every internal link and anchor resolves")
    return 0


if __name__ == "__main__":
    sys.exit(main())
